pipeline {
    agent {
        node {
            label 'slave1'
        }
    }
    stages {
        tage('Git Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'github access', url: 'https://github.com/kalagaGangadhar/Project-Management.git']]])
                sh 'pwd'
            }
        }
        stage('change directory') {
            steps {
                dir('Project/Task')
                sh 'pwd'
            }
        }
        stage('Terraform init') {
            steps {
                sh 'terraform init'
                sh 'pwd'
            }
        }
        stage('Terraform validate') {
            steps {
                sh 'terraform validate'
                sh 'pwd'
            }
        }
        stage('Terraform plan') {
            steps {
                sh 'terraform plan'
                sh 'pwd'
            }
        }
        stage('Terraform apply/destroy') {
            parallel {
                stage('Terraform apply') {
                    when {
                        expression {
                            "$State" == "apply"
                        }
                    }
                    steps {
                        sh 'terraform apply --auto-approve'
                    }
                }
                stage('Terraform destroy') {
                    when {
                        expression {
                            "$State" == "destroy"
                        }
                    }
                    steps {
                        sh 'terraform destroy --auto-approve'
                    }
                }
            }
        }
    }
}