pipeline{
    agent {
      node {
	label 'slave1'
    }
}
    stages{
        stage('pre-build step') {
            steps {
		sh '''
                echo "Pre Build Step for Webhook Trigges the pipeline on push event"
		'''
	    }
     	}
        stage('Git Checkout'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'github access', url: 'https://github.com/kalagaGangadhar/Project-Management.git']]])
            }
        }

        stage('Terraform init') {
                    steps {
                        sh 'terraform init'
                    }
                }

        stage('Terraform validate') {
                            steps {
                                sh 'terraform fmt'
                                sh 'terraform validate'
                            }
                        }

        stage('Terraform plan') {
                            steps {
                                sh 'terraform plan'
                            }
                        }
        stage('Terraform apply/destroy') {
           parallel{
             stage('Terraform apply'){
               when{
                 expression { "$State" == "apply"}
               }
               steps{
                 sh 'terraform apply --auto-approve'
               }
             }

             stage('Terraform destroy'){
                            when{
                              expression { "$State" == "destroy"}
                            }
                            steps{
                              sh 'terraform destroy --auto-approve'
                            }
                          }
           }

    }
}